# Generated by Django 3.1.2 on 2020-11-01 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_auto_20201101_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author_of_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author_of_post',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='user',
            new_name='author_of_reaction',
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('author_of_reaction', 'post')},
        ),
    ]
